# PyIPF
This package is a simple, lightweight function for Iterative Proportional Fitting (IPF) in Python, leveraging numpy.

## Examples

In [1]:
import numpy as np
import pyipf

Generate a dummy 2-D matrix, calculate the marginals and fit another random matrix to these marginals.

In [2]:
dims = (4, 5)

# Target matrix
M = np.random.lognormal(size=dims)

m0 = M.sum(axis=0)
m1 = M.sum(axis=1)
marginals = [m0, m1]

# Initial matrix
M0 = np.random.lognormal(size=dims)

In [3]:
M1 = pyipf.ipf(M0, marginals)
M1

array([[1.48113251, 0.55856014, 2.08747773, 0.56021773, 1.03206795],
       [0.69822861, 1.55448881, 4.81882003, 1.21310727, 0.97432328],
       [1.09937593, 3.3163754 , 4.32870335, 3.96402992, 2.94410888],
       [0.14960558, 0.41166272, 2.26674958, 0.3578438 , 0.24096606]])

Compare fitted and target marginals:

In [4]:
print('Target, axis 0:\n', m0)
print('Marginal of adjusted matrix, axis 0:\n', M1.sum(axis=0), '\n')
print('Target, axis 1:\n', m1)
print('Marginal of adjusted matrix, axis 1:\n', M1.sum(axis=1))

Target, axis 0:
 [ 3.4286093   5.84075267 13.50264179  6.09463002  5.19121148]
Marginal of adjusted matrix, axis 0:
 [ 3.42834263  5.84108707 13.50175069  6.09519871  5.19146617] 

Target, axis 1:
 [ 5.71945605  9.258968   15.65259348  3.42682773]
Marginal of adjusted matrix, axis 1:
 [ 5.71945605  9.258968   15.65259348  3.42682773]


Generate a dummy 3-D matrix, calculate the marginals and fit another random matrix to these marginals, specifying convergence tolerance.

In [5]:
dims = (3, 4, 5)

# Target matrix
M = np.random.lognormal(size=dims)

m0 = M.sum(axis=0)
m1 = M.sum(axis=1)
m2 = M.sum(axis=2)
marginals = [m0, m1, m2]

# Initial matrix
M0 = np.random.lognormal(size=dims)

In [6]:
M1 = pyipf.ipf(M0, marginals, tol_convg=1e-6, convg='relative')
M1

array([[[ 6.90520184,  0.19622997,  0.50768919,  0.13275736,
          0.9293064 ],
        [ 0.32222376,  0.47374635,  1.4574094 ,  0.41314916,
          1.49357124],
        [ 5.50093779,  2.30097208,  0.83291671,  2.06222807,
          4.76761113],
        [ 1.05853495,  1.48787403,  2.28223884,  0.82394211,
          0.37148028]],

       [[ 2.34378896,  1.64056743,  1.00887538, 11.19510664,
          2.13286317],
        [ 3.02598556,  2.57129926,  0.49945323,  0.71899295,
          2.69610131],
        [ 1.43239667,  0.39328493,  1.32521908,  5.47897728,
          1.20718297],
        [ 0.25718674,  3.29791467,  0.2144161 ,  0.72681184,
          0.09525226]],

       [[ 1.53875623,  0.99582773,  0.81303361,  3.33673096,
          1.07546425],
        [ 0.08839578,  0.37560561,  0.52715961,  0.14010666,
          3.33154548],
        [ 2.47620309,  1.12473498,  0.05954928,  0.37551812,
          0.81860914],
        [ 0.17524599,  0.85283704,  0.58042856,  0.05153553,
          0

Compare fitted and target marginals:

In [7]:
print(m0)
print(M1.sum(axis=0), '\n')
print(m1)
print(M1.sum(axis=1), '\n')
print(m2)
print(M1.sum(axis=2), '\n')

[[10.7877543   2.83262409  2.32959835 14.66458809  4.13763429]
 [ 3.43660833  3.42064997  2.48402144  1.27224901  7.52121662]
 [ 9.40953466  3.81899429  2.21768484  7.91672545  6.79340209]
 [ 1.49096686  5.63862699  3.07708226  1.60229052  0.97929161]]
[[10.78774703  2.83262512  2.32959818 14.66459496  4.13763382]
 [ 3.4366051   3.42065123  2.48402225  1.27224877  7.52121803]
 [ 9.40953755  3.81899199  2.21768507  7.91672348  6.79340324]
 [ 1.49096768  5.63862573  3.0770835   1.60228948  0.97929185]] 

[[13.78690471  4.45882067  5.08025209  3.43207544  7.56196774]
 [ 7.05935806  7.90306938  3.04796382 18.11988552  6.13139968]
 [ 4.27860138  3.34900529  1.98017098  3.90389211  5.73817719]]
[[13.78689833  4.45882243  5.08025414  3.4320767   7.56196906]
 [ 7.05935793  7.90306629  3.04796379 18.11988872  6.13139972]
 [ 4.27860109  3.34900536  1.98017106  3.90389127  5.73817816]] 

[[ 8.67118475  4.16009991 15.46466578  6.02407021]
 [18.32120159  9.51183232  9.83706094  4.59158162]
 [ 7.759